### PR TITLE
Emotes - add create/list/delete slash commands

### PR DESCRIPTION
**Pull request by lenisko**
Add ability to create, list and delete (only created by bot) emotes using slash commands (admin only)

### CODE REVIEW

**Comment by TMHBOFH** [comment]
please also update the Dockerfile
```
COPY default.toml /porygon/
+ COPY /emojis /porygon/emojis
COPY /templates /porygon/templates
```

thanks

**Comment by lenisko** [comment]
@TMHBOFH I'm not an Docker expert, but you don't want to put those files in image but bind them. Check compose example.

**Comment by TMHBOFH** [comment]
@lenisko 
I know what you mean, but would it run if there wasn't even an empty emojis folder?

As I understand it, at least the empty emojis folder schuld be in the image or?

**Comment by lenisko** [comment]
@TMHBOFH it will start just fine, those are required once you want to run `create-emotes` command.

**Review by na-ji — APPROVED** [review]
Overall, the commands work well. It does the job. Now the next step would be to also use the emojis that were uploaded. :)

**Comment by lenisko** [comment]
Thanks :) 

Yeah, fairly easy to create a mapping of emote name <> config and return it in message. Good for someone else!

**Pull request merged**
